config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  post 'signup', to: 'students#create'
  get 'signup', to: 'students#new'
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  resources :students
  resources :courses
  get 'about', to: 'pages#about'
  get 'courses', to:'courses#index'
  root 'welcome#home'
  get 'courses/new', to: 'courses#new'
  post 'course_enroll', to: 'student_courses#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: { minimum: 5, maximum: 50 }
    validates :short_name, presence: true, length: { minimum: 3, maximum: 150 }
    validates :description, presence: true, length: { minimum: 10, maximum: 500 }
    has_many :student_courses
    has_many :students, through: :student_courses, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, 
              uniqueness: { case_sensitive: false },
              length: { minimum: 3, maximum: 25 }

    validates :password, presence: true,
              length: { minimum: 6, maximum: 25 }

              VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true,
              uniqueness: { case_sensitive: false },
              length: { maximum: 50 },
              format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    has_many :student_courses
    has_many :courses, through: :student_courses, dependent: :destroy
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    current_user
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_admin, except: [:show,:index]
#   before_action :require_same_student, only: [:create, :new, :edit, :update, :destroy]
  
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
      @course = Course.new(course_params)
      if @course.save
          flash[:success] = "You have successfully created this course"
          redirect_to courses_path
      else
          render 'new'
      end
  end


  def edit
  end

    def update
        if @course.update(course_params)
            flash[:success] = "Your profile successfully edited this course"
            redirect_to courses_path
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        flash[:success] = "Your course was successfully deleted"
        redirect_to courses_path
    end

    private

    def set_student
        @course = Course.find(params[:id])
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:success] = "Only admins can perform that action"
            redirect_to courses_path
        end
    end

    # def require_same_student
    #     if current_user != !current_user.admin?
    #         flash[:success] = "You cannot perform that action"
    #         redirect_to root_path
    #     end
    # end

    def course_params
        params.require(:course).permit(:name, :short_name, :description)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only: %i[new create]

  def new; end

  def create
    student = Student.find_by(email: params[:logins][:email].downcase)
    if student&.authenticate(params[:logins][:password])
      session[:student_id] = student.id
      flash[:success] = 'You have successfully logged in'
      redirect_to student
    else
      flash.now[:danger] = 'Something was wrong with your information'
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about; end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    if current_user.courses.include?(course_to_add)
      flash[:notice] = 'Something was wrong with your enrollment'
      redirect_to root_path
    else
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "You have successfully enrollrd in #{course_to_add.name}"
      redirect_to current_user
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user
    before_action :set_student, only: [:show, :edit, :update]
    before_action :require_same_student, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def index
        @students = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            # flash[:success] = "You have successfully signed up #{@student.name}"
            # redirect_to student_path(@student)
            redirect_to login_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @student.update(student_params)
            flash[:success] = "Your profile was successfully edited"
            redirect_to student_path(@student)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        flash[:success] = "Your profile was successfully deleted"
        redirect_to students_path
    end

    private

    def set_student
        @student = Student.find(params[:id])
    end

    def require_same_student
        if current_user != @student and !current_user.admin?
            flash[:success] = "You can only edit your own profile"
            redirect_to student_path(current_user)
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:success] = "Only admins can perform that action"
            redirect_to root_path
        end
    end

    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_user
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if logged_in?
      link_to('logout', logout_path, method: :delete)
    else
      link_to('login', login_path)
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/edit.html.erb
<main class="container">
    <%= render "shared/error", obj: @course %>
    <%= render 'form'%>
</main>

app/views/courses/index.html.erb
<% flash.each do |key, message|%>
<div class='container'>
    <div class='row sign-up-form'>
        <div class='col s12 m12 l12'>
            <div class='card-panel green accent-1' id='fade-out-target'>
                <span class='white-text'>
                    <%= message %>
                </span>
            </div>
        </div>
    </div>
</div>
<% end %>
<main class="container">
    <div class='row'>
        <div class='col s12'>
            <h1 class='center-align'>Course Listing</h1>
        </div>
    </div>


    <% if logged_in? && current_user.admin? %>
    <%= link_to  "Create New Courses", new_course_path %>
    <% end %>
    <div class="row">
        <% @courses.each do |course| %>
        <div class="col s12 m6 ">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">
                        <%= course.name %>:<%= course.short_name %>
                    </span>
                    <p>
                        <%= course.description %>
                    </p>
                </div>
                <div class="card-action">
                    <% if logged_in? && !(current_user.courses.include?(course)) %>
                    <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
                    <% end %>
                    <%= link_to  "Info", course_path(course) %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</main>

app/views/courses/show.html.erb
<% flash.each do |key, message|%>
<div class='container'>
    <div class='row sign-up-form'>
        <div class='col s12 m12 l12'>
            <div class='card-panel green accent-1' id='fade-out-target'>
                <span class='white-text'>
                    <%= message %>
                </span>
            </div>
        </div>
    </div>
</div>
<% end %>
<main class="container">
    <div class='row sign-up-form'>
        <div class="col s12 m6 l6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">
                        Name: <%= @course.name %>
                    </span>
                    <p>
                        Tools: <%= @course.short_name %>
                    </p>
                    <p>
                        Description: <%= @course.description %>
                    </p>
                </div>
                <div class="card-action">
                    <% if logged_in? && !(current_user.courses.include?(@course)) %>
                    <%= link_to "Enroll", course_enroll_path(course_id: @course.id), method: :post %>
                    <% end %>
                </div>
            </div>
            <%# if logged_in? && !current_user.admin? %>
            <% if logged_in? && (current_user == @student || current_user.admin?) %>
            <%= link_to '<i class="material-icons left">create</i>Edit Profile'.html_safe, edit_course_path(@course), class: "waves-effect waves-light btn" %>
            <% end %>
        </div>

        <% if logged_in? && (current_user.courses.include?(@course)) %>
        <%# <div class="row"> %>
        <div class="col s12 m6 l6">
            <div class="card-panel teal">
                <span class="white-text">Thanks for enrolling in this course.
                    Contents of this course will be uploaded very soon. Do well to inform your friends to enroll.
                </span>
            </div>
        </div>
        <%# </div> %>
        <% end %>
    </div>

</main>

app/views/layouts/_footer.html.erb
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Tech Club</h5>
                    <p class="grey-text text-lighten-4">Our mission is to produce world class developers.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Get in Touch</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="https://github.com/Elijahscriptdev"><i class="fab fa-github grey-text text-lighten-3"></i></a></li>
                        <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/elijah-obominuru-0b730b143/"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a class="grey-text text-lighten-3" href="https://twitter.com/ElijahObominuru"><i class="fab fa-twitter"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2020 Copyright Tech Club
                <%# <a class="grey-text text-lighten-4 right" href="#!">About</a> %>
                <%= link_to  "About", about_path, class: "grey-text text-lighten-4 right" %>
            </div>
        </div>
    </footer>

app/views/layouts/_navigation.html.erb
    <header>
        <ul id="dropdown1" class="dropdown-content">

            <li>
                <%= session_link %>
            </li>

            <% if logged_in? %>
            <li class="divider"></li>
            <li><%= link_to  "Profile", student_path(current_user) %></li>
            <% else%>
            <li>
                <%= link_to "Signup", new_student_path %>
            </li>
            <% end %>

        </ul>

        <ul id="dropdown2" class="dropdown-content">
            <li>
                <%= link_to  "Home", root_path %>
            </li>
            <li>
                <%= session_link %>
            </li>
            <% if logged_in? %>
            <li class="divider"></li>
            <li><%= link_to  "Profile", student_path(current_user) %></li>
            <% else%>
            <li>
                <%= link_to "Signup", new_student_path %>
            </li>
            <% end %>
        </ul>

        <ul class="sidenav" id="mobile-demo">
            <li>
                <%= link_to  "Home", root_path %>
            </li>
            <li><%= link_to  "Courses", courses_path %></li>
            <% if logged_in? %>
            <li><%= link_to  "Students", students_path %></li>
            <% end %>
            <li><a href="sass.html">Contact Us</a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>

        <nav>
            <div class="nav-wrapper container">
                <%= link_to  "Tech Club", root_path, class: "brand-logo right"  %>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <li>
                        <%= link_to  "Home", root_path %>
                    </li>
                    <li><%= link_to  "Courses", courses_path %></li>
                    <% if logged_in? %>
                    <li><%= link_to  "Students", students_path %></li>
                    <%= "Admin" if current_user.admin? %>
                    <% end %>

                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
            </div>
        </nav>
    </header>

app/views/pages/about.html.erb
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2">Tech Club</h1>
            <div class="row center">
                <h5 class="header col s12 light">Our mission is to produce world class developers.</h5>
            </div>
            <div class="row center">
                <%# <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a> %>
                <%= link_to "Get Started", new_student_path, class: "btn-large waves-effect waves-light teal lighten-1" %>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587691994/woman-sitting-while-operating-macbook-pro-1181676_adsqot.jpg" alt="Unsplashed background img 1"></div>
</div>


<div class="container">
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
                    <h5 class="center">Speeds up development</h5>

                    <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">group</i></h2>
                    <h5 class="center">User Experience Focused</h5>

                    <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
                    <h5 class="center">Easy to work with</h5>

                    <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
                </div>
            </div>
        </div>

    </div>
</div>


<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587666427/men-working-at-night-256219_tus5xy.jpg" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
    <div class="section">

        <div class="row">
            <div class="col s12 center">
                <h3><i class="mdi-content-send brown-text"></i></h3>
                <h4>Contact Us</h4>
                <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
            </div>
        </div>

    </div>
</div>


<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587457727/bnb9twcehpoisvawtxbx.jpg" alt="Unsplashed background img 3"></div>
</div>

app/views/students/edit.html.erb
<main class="container">
    <%= render "shared/error", obj: @student %>
    <%= render 'form'%>
</main>

app/views/students/show.html.erb
<% flash.each do |key, message|%>
<div class='container'>
    <div class='row sign-up-form'>
        <div class='col s12 m12 l12'>
            <div class='card-panel green accent-1' id='fade-out-target'>
                <span class='white-text'>
                    <%= message %>
                </span>
            </div>
        </div>
    </div>
</div>
<% end %>
<main class="container">
    <div class='row sign-up-form'>
        <div class="col s12 m6 l6">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">
                        Name: <%= @student.name %>
                    </span>
                    <p>
                        Email: <%= @student.email %>
                    </p>
                    <p>
                        Course Enrollments:
                        <% if @student.courses.empty? %>
                        None
                        <% else %>
                        <ul>
                            <% @student.courses.each do |course| %>
                            <li>
                                <%= course.name %> | <%= link_to  "View course content", course_path(course) %>
                            </li>
                            <% end %>
                        </ul>
                        <% end %>
                    </p>
                </div>
            </div>
            <% if logged_in? && (current_user == @student || current_user.admin?) %>
            <%= link_to '<i class="material-icons left">create</i>Edit Profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
            <% end %>
        </div>
    </div>
</main>

app/views/welcome/home.html.erb
<div id="container" class="frame">
    <div class="herotext bg" id="first">
        <h3 class="center-align">Lets start your</h3>
        <h2 class="center-align">Software Development Career</h2>
        <p class="center-align">How would you like to get started?</p>
        <p class="center-align"><%= link_to "Signup Now", new_student_path, class:"waves-effect waves-light btn" %></p>
    </div>
    <div class=" herotext bg" id="second">
        <h3 class="center-align">Best Place For</h3>
        <h2 class="center-align">Software Engineering</h2>
        <p class="center-align">How would you like to get started?</p>
        <p class="center-align"><%= link_to "Signup Now", new_student_path, class:"waves-effect waves-light btn" %></p>
    </div>
    <div class="herotext bg" id="third">
        <h3 class="center-align">Lets start your</h3>
        <h2 class="center-align">Software Development Career</h2>
        <p class="center-align">How would you like to get started?</p>
        <p class="center-align"><%= link_to "Signup Now", new_student_path, class:"waves-effect waves-light btn" %></p>
    </div>
</div>
<div class="center-align">
    <h1>Our Courses</h1>
</div>

<div class="row">
    <div class="col s12 m6 l4">
        <div class="card hoverable">
            <div class="card-image">
                <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587666843/woman-holds-blue-laptop-computer-while-sits-on-sofa-inside-1181267_mpyyvh.jpg">
                <span class="card-title ">Front-End Development</span>
            </div>
            <div class="card-content">
                <p>Front-end web development, also known as client-side development is the practice of producing HTML,
                    CSS and JavaScript for a website or Web Application so that a user can see and interact with them directly.</p>
            </div>
            <div class="card-action">
                <%= link_to "view courses", courses_path %>
            </div>
        </div>
    </div>
    <div class="col s12 m6 l4">
        <div class="card hoverable">
            <div class="card-image">
                <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587666396/screen-coding-programming-web-design-2061168_twdw9f.jpg">
                <span class="card-title ">Back-End Development</span>
            </div>
            <div class="card-content">
                <p>Backend development languages handle the ‘behind-the-scenes’ functionality of web applications.
                    It’s code that connects the web to a database, manages user connections,
                    and powers the web application itself.</p>
            </div>
            <div class="card-action">
                <%= link_to "view courses", courses_path %>
            </div>
        </div>
    </div>
    <div class="col s12 m6 l4">
        <div class="card hoverable">
            <div class="card-image">
                <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587456958/vx16n09jafmbb10msb2x.jpg">
                <span class="card-title ">Fullstack Development</span>
            </div>
            <div class="card-content">
                <p>Full-stack developers are experts in both the front-end and back-end;
                    so, the full stack of technology that makes up a website.
                    They are proficient in both front-end and back-end languages and frameworks.</p>
            </div>
            <div class="card-action">
                <%= link_to "view courses", courses_path %>
            </div>
        </div>
    </div>
</div>

<div class="parallax-container">
    <div class="parallax"><img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587691344/photo-of-woman-using-laptop-3194518_mqnlkg.jpg"></div>
</div>
<div class="section white">

    <div class="row">
        <h2 class="header center-align">Final Projects</h2>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class=" card-image">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587697047/FireShot_Capture_071_-_Enfant_-_School_and_Kindergarten_WordPress_Theme_by_zoutula_-_ThemeFo__-_themeforest.net_blaumx.png">
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587697047/FireShot_Capture_069_-_Rythmo_-_School_of_Arts_Music_School_WordPress_Theme_by_ThemeREX__-_themeforest.net_ciu3kb.png">
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587697047/FireShot_Capture_070_-_DreeveX_Driving_School_WordPress_Theme_by_Esmet_-_ThemeForest__-_themeforest.net_s8guo7.png">
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image ">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587697047/FireShot_Capture_074_-_Chaos_-_Bag_Store_HTML5_Template_by_HasTech_-_ThemeForest_-_themeforest.net_wmcciy.png">
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image ">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587699674/FireShot_Capture_075_-_Especio_-_Personal_Gutenberg_Food_Blog_WordPress_Theme_by_ThemeREX__-_themeforest.net_o3xml6.png">
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image ">
                    <img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587699685/FireShot_Capture_076_-_Julia_A_Steady_Food_Blog_WordPress_Theme_by_pixelgrade_-_ThemeFores__-_themeforest.net_kvuhev.png">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="parallax-container">
    <div class="parallax"><img src="https://res.cloudinary.com/elijjaaahhhh/image/upload/v1587691336/man-in-grey-sweater-holding-yellow-sticky-note-879109_1_m5bys8.jpg"></div>
</div>

<%# <div class="row">
    <div class="col s12 m9 l10">
        <div id="introduction" class="section scrollspy">
            <p>Content </p>
        </div>

        <div id="structure" class="section scrollspy">
            <p>Content </p>
        </div>

        <div id="initialization" class="section scrollspy">
            <p>Content </p>
        </div>
    </div>
    <div class="col hide-on-small-only m3 l2">
        <ul class="section table-of-contents">
            <li><a href="#introduction">Introduction</a></li>
            <li><a href="#structure">Structure</a></li>
            <li><a href="#initialization">Intialization</a></li>
        </ul>
    </div>
</div> %>

<!-- Location -->
<div class="center-align white">
    <h1>Location</h1>
</div>
<div class="container-fluid grey lighten-5" id="location">

    <%# <div class="col subtitle">Map</div> %>
    <div class="row margin">
        <div class="col m6 l6 s12">
            <div class="maps">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.7112395536437!2d3.454792113812731!3d6.431128495347092!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf506fbc6430b%3A0x626226e105c36107!2sOniru%20Estate%20Lekki!5e0!3m2!1sen!2sbr!4v1587671424224!5m2!1sen!2sbr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>


        <div class="col m6 l6 s12">
            <%# <div class="col s12 m12 l12 "> %>
            <h4>Contact Us</h4>
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s12 m6 l6">
                            <input id="first_name" type="text" class="validate">
                            <label for="first_name">First Name</label>
                        </div>
                        <div class="input-field col s12 m6 l6">
                            <input id="last_name" type="text" class="validate">
                            <label for="last_name">Last Name</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="email" type="email" class="validate">
                            <label for="email">Email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <textarea id="textarea1" class="materialize-textarea"></textarea>
                            <label for="textarea1">Comments</label>
                        </div>
                    </div>
                    <div class="row">
                        <a class="waves-effect waves-light btn">Submit</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<%# </div> %>
<!-- End Location -->
<%# </div> %>
<!-- End Location -->